### ISSUE TITLE
Better heading for faceting section

### ISSUE THREAD

**Issue by Otterfan** [BCDigSchol/connolly-omeka-theme#11]
Currently reads "Limit your search". Luke suggests "Limit by:". Do we need any text there at all? Are we familiar enough with left-hand facets now?

**Comment by LukeGaudreau** [comment]
Good point, maybe it's not needed. Whatever is decided, I vote for consistency. I'd like to remove or change the label in other systems to match. I'll consider adding to testing for New Primo UI.

**Comment by annakijas1** [comment]
I think we should remove the "Limit your search" text. Change the facet that is generically labeled "type" to reflect "Song & Tune Type" For example, see mockup:


![screen shot 2016-08-04 at 9 54 47 am](https://cloud.githubusercontent.com/assets/6841932/17404404/819578f0-5a29-11e6-9871-6b9b581d7ef9.png)

**Comment by annakijas1** [comment]
Updated to "Limit by:"
