### ISSUE TITLE
Search results squished on small screens

### ISSUE THREAD

**Issue by Otterfan** [BCDigSchol/connolly-omeka-theme#12]
The SolrSearch results list is very non-responsive.

**Comment by annakijas1** [comment]
Maybe we can suppress the description that appears under the tune title within the search results so that it is less cluttered on small screens?

**Comment by annakijas1** [comment]
from @ChristopherHP: a 30 sec mock up of what the search results could look like if we suppress the descriptions. I also made the left floating column 100% width, so nothing was squished. 

![8-3-2016 1-09-27 pm](https://cloud.githubusercontent.com/assets/6841932/17376182/67adfa90-5982-11e6-99bd-30705db950e7.png)

**Comment by ChristopherHP** [comment]
Added media query to main style sheet to mimic results mock up above.
