### ISSUE TITLE
Advanced search layout issue

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/connolly-omeka-theme#18]
When you click on the blue ... part of the search bar, the instructions for advance search fall behind the navigational menu. This happens on all pages except the home page, where the background image is bigger.
![screen shot 2016-08-04 at 10 58 09 am](https://cloud.githubusercontent.com/assets/6841932/17406657/5e83c99e-5a32-11e6-8439-addaab099992.png)

**Comment by ChristopherHP** [comment]
Added z-index to menu div.
