### ISSUE TITLE
Tags page 

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/connolly-omeka-theme#19]
When you click on the "Browse by Tag" in the secondary nav and it opens a page with the list of playlists, the space is too small and it causes the tags to overlap. 
![screen shot 2016-08-08 at 11 35 40 am](https://cloud.githubusercontent.com/assets/6841932/17485655/42182e76-5d5c-11e6-97c0-6c5c6476776d.png)

**Comment by ChristopherHP** [comment]
Added class to make all items under this list appear as the same size.
