### ISSUE TITLE
Search options not necessary

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/connolly-omeka-theme#22]
Keyword, Boolean, and Exact Match options can be suppressed or disabled. There is no difference between these searches. You can use boolean and quotations for exact matches without having to select between the three options in the search bar.
![screen shot 2016-08-15 at 2 31 09 pm](https://cloud.githubusercontent.com/assets/6841932/17674855/563abe16-62f5-11e6-8c4d-bfb4240aec31.png)

**Comment by annakijas1** [comment]
We would like to replace the section where the radio buttons and text currently exist with some search tips for the user.

**Comment by ChristopherHP** [comment]
It's possible to use CSS to hide that section. I'm not sure if I'd be able to add in additional info in it's place.

**Comment by Otterfan** [comment]
I found this text, and we can definitely replace it. @annakijas1, what text would you like there?

**Comment by annakijas1** [comment]
What do you think of adding these search tips:

Search using:
- Keyword
- AND, OR, NOT (i.e. Jigs NOT Hornpipes)
- Quotation marks (i.e. "Jerry o'sullivan")
- Wildcard character \* (i.e. Redican*)

**Comment by Otterfan** [comment]
I took a go at this. How does it look?

**Comment by annakijas1** [comment]
Looks good! Can we add the "advanced search" option that appeared in the previous version?

**Comment by Otterfan** [comment]
Whoops! I knew I deleted something important.

**Comment by annakijas1** [comment]
@Otterfan advanced search link still not showing up - do you need to push the change?

**Comment by Otterfan** [comment]
Sorry, it should be up there now.
