### ISSUE TITLE
Collection Show/Browse Pages

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/connolly-omeka-theme#24]
When you click on the item listed under "Collection" in Item Record it takes you the the collection show page - which is a results page and is confusing to the user. (ex: http://connollymusiccollection.bc.edu/collections/show/23) 
Should go to the collection browse page instead (ex: http://connollymusiccollection.bc.edu/items/browse?collection=23)

**Comment by annakijas1** [comment]
I think that I may have fixed this. In show.php, I changed "link_to_items_in_collection" instead of linking to the collection list.

  `  <?php if(metadata('item','Collection Name')): ?>
            <div id="collection" class="element">
              <h3><?php echo __('Collection'); ?></h3>
              <div class="element-text"><?php echo link_to_items_in_collection(); ?></div>
            </div>
         <?php endif; ?>`

**Comment by Otterfan** [comment]
Try [link_to_items_in_collection](http://omeka.readthedocs.io/en/latest/Reference/libraries/globals/link_to_items_in_collection.html?highlight=link_to_items_in_collection).

**Comment by Otterfan** [comment]
Apparently the useful function was [link_to_items_to_browse](http://omeka.readthedocs.io/en/latest/Reference/libraries/globals/link_to_items_browse.html?highlight=link_to_browse).
