### ISSUE TITLE
VIAF ID in Subject heading

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/connolly-omeka-theme#29]
When the VIAF ID is linked in the subject heading, it generates the "VIAF ID" term and icon twice. 
See example:

![screen shot 2016-08-30 at 11 39 00 am](https://cloud.githubusercontent.com/assets/6841932/18095904/78a0e874-6ea6-11e6-8889-6102b2a31036.png)

**Comment by annakijas1** [comment]
It seems that the way the VIAF ID and Icon were added to the CSS is causing havoc when I add it to anything other than the "Creator" field. See what happens when it is added to the subject heading field:
![screen shot 2016-08-30 at 11 45 09 am](https://cloud.githubusercontent.com/assets/6841932/18096168/5622530e-6ea7-11e6-99ea-aa625e5b59e8.png)

**Comment by ChristopherHP** [comment]
I have added an identifier, so only VIAF links in the class "element-text" will have the VIAF ID and Icon. This should fix the issue of it showing up a number of times on searches.

**Comment by annakijas1** [comment]
What seems to happen is that because the DC:Subject field is linked to enable searching across subject headings, it is generating the Viaf ID after the name (i.e. Allen, Ethan Viaf ID) and then after the actual ID. Because it is in the class "element-text" it generate it twice. Can this be suppressed in the CSS or modified?

**Comment by ChristopherHP** [comment]
Adjusted CSS selector to only add the VIAF icon to the links that begin with "http://viaf.org", and to not add this to the links that simply contain "viaf.org".
