### ISSUE TITLE
Hide "Search by Exhibit"

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/connolly-omeka-theme#38]
Hide "Search by Exhibit" on [Search page](http://connollymusiccollection.bc.edu/items/search) using CSS. @ChristopherHP

**Comment by ChristopherHP** [comment]
I believe I have hidden the field. However, there were no CSS identifiers for that exact field, so I had to identify them based on the classes "alpha" and "omega". Hopefully, these do not appear anywhere else. if they do, and my changes effected those areas, we'll need another solution.

**Comment by annakijas1** [comment]
Yes, it looks like it has been hidden! We'll let you know if it affects anything incorrectly.
