### ISSUE TITLE
Index VIAF IDs

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/connolly-omeka-theme#39]
Can we hide VIAF IDs in the Index under [Subject](http://connollymusiccollection.bc.edu/references/subject)? @ChristopherHP

**Comment by ChristopherHP** [comment]
Are you referring to the numbers themselves? I.e. Ó Canainn, Tomás **11112354**?
If so, it is being pulled in as text, there's nothing to identify it using CSS.

**Comment by annakijas1** [comment]
Yes, the numbers. Can we suppress them from appearing? Ben did this for the citations.

**Comment by Otterfan** [comment]
We can suppress the VIAF ID from appearing in the subject line, but the VIAF bit (including the link) will still be indexed. For example, no VIAF in the subject links:

![image](https://cloud.githubusercontent.com/assets/210404/18851474/35499aa2-840a-11e6-8f56-09378fc1a6a8.png)

but clicking on Cronin, Johnny takes you to a page with a strange browser header:

![image](https://cloud.githubusercontent.com/assets/210404/18851489/502850a2-840a-11e6-88e7-91edfe624f30.png)

**Comment by annakijas1** [comment]
I'm referring to the Viaf Id that appears in the Index section (reference plugin). We want to keep the Viaf ID in the subject fields within the item record but not have it appear after the name on the subject list generated by the Index.

**Comment by annakijas1** [comment]
See the index under subject: http://connollymusiccollection.bc.edu/references/subject - this is where the VIAF IDs are pulled in as a string. Can we hide them only here and not in the item record? @Otterfan @ChristopherHP 

![screen shot 2016-09-27 at 9 02 37 am](https://cloud.githubusercontent.com/assets/6841932/18874821/44528126-8491-11e6-87ac-60b34cc576ab.png)

**Comment by Otterfan** [comment]
Sorry about that! We can override the Reference plugin's view to fix this.
