### ISSUE TITLE
Subject Index character issue

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/connolly-omeka-theme#45]
[Index (Reference Plugin) ](http://connollymusiccollection.bc.edu/references) is putting some names in the #0-9 section of the index in both Subject and Names pages. @Otterfan 
In the Subject Index, the #0-9 lists one name at the top and then 2 at the end of the list. This is happening because when you look at the subject field in the Item record for these names the diacritic is being converted into a character. Can this be fixed? 
![screen shot 2016-09-30 at 10 32 46 am](https://cloud.githubusercontent.com/assets/6841932/18995259/7650e8c4-86f9-11e6-8548-f8764d0d3b27.png)
![screen shot 2016-09-30 at 10 32 54 am](https://cloud.githubusercontent.com/assets/6841932/18995261/78722c26-86f9-11e6-9b64-d3a5f1f003c7.png)

**Comment by Otterfan** [comment]
This one is strange. Even with the spacing issue (#46) fixed, Ó Canainn still appears in a "#0-9" field at the start of the list while Ó Laidhigh and Ó Muineacháin appear at the end of the list.
