### ISSUE TITLE
Name Index spacing issue

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/connolly-omeka-theme#46]
@Otterfan In the Name Index - there are names that are listed under the #0-9 section because when they were pushed to the Omeka DB in the Relation Field a space was added before the last name. I checked this in the Item Records in the Relation Field and indeed there is a space. I fixed a few and they were bumped from the #0-9 list to the alphabetical section they belong. Can you automate this, because there is a long list that would need to be fixed by hand.
![screen shot 2016-09-30 at 10 13 14 am](https://cloud.githubusercontent.com/assets/6841932/18995288/975590d8-86f9-11e6-94b9-4728ad076101.png)

**Comment by Otterfan** [comment]
Spaces removed.
