### ISSUE TITLE
Add link to additional search tips

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/connolly-omeka-theme#50]
Add text and link to additional search tips (created a search tips page) in the box that appears when you select the ... in the search box area. See example.
<img width="692" alt="screen shot 2017-02-20 at 11 19 52 am" src="https://cloud.githubusercontent.com/assets/6841932/23133299/a11f2608-f75e-11e6-8a5c-c19d41e4db24.png">

**Comment by Otterfan** [comment]
Got it.
