### ISSUE TITLE
Citation is partially cut off

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/connolly-omeka-theme#51]
Just noticed that when you view an item record, the citation is partially cut off. For example [see](https://connollymusiccollection.bc.edu/document/461). The "1" in "461" is cut-off. This occurs in other item records when the citation is long.
<img width="465" alt="screen shot 2017-05-29 at 7 08 03 pm" src="https://cloud.githubusercontent.com/assets/6841932/26563580/288616ca-44a2-11e7-9c91-9441aa0a117c.png">

**Comment by ChristopherHP** [comment]
Just to follow up, the reason is because the section's CSS is set to
overflow: hidden. On my browser, the citation fits, though.

Chris Houston-Ponchak

*Web Design & Communications Specialist*
*O'Neill Library, Boston College*

**Comment by annakijas1** [comment]
Hi Chris,

This is still happening when viewing the item record on my laptop and other
computers. Can you see if this can be adjusted?

Anna
